### ISSUE TITLE
vgrouter always use old package

### ISSUE THREAD

**Issue by darkautism** [vugu/vgrouter#1]
``` bash
# main
./main_wasm.go:27:19: undefined: domrender.New
```

vgrouter's go.mod
require github.com/vugu/vugu v0.1.1-0.20200330101439-908c5990954b

This version domrender do not have any method call New
https://github.com/vugu/vugu/blob/908c5990954b5357e682b07b4a1b355d091bcf4b/domrender/renderer-js.go

It seems method added 3 hour ago but vgrouter go.mod not update yet.

https://github.com/vugu/vugu/commit/606e61db59cc6ecbd9a4a60d53cf79b0abe3b5e9

**Comment by bradleypeabody** [comment]
Thanks, I just pushed a fix for this.  Let me know if it works for you.
